/**
 * @file heddokoPacket.cs
 * @brief Functionalities required to operate it.
 * @author Sergey Slepokurov (sergey@heddoko.com)
 * @date 12 2016
 * Copyright Heddoko(TM) 2017,  all rights reserved
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled

// Generated from: heddokoPacket.proto
namespace DAL.Models.MongoDocuments
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ImuDataFrame")]
  public partial class ImuDataFrame : global::ProtoBuf.IExtensible
  {
    public ImuDataFrame() {}
    
    private uint _imuId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"imuId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint imuId
    {
      get { return _imuId; }
      set { _imuId = value; }
    }
    private uint? _sensorMask;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sensorMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sensorMask
    {
      get { return _sensorMask?? default(uint); }
      set { _sensorMask = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sensorMaskSpecified
    {
      get { return this._sensorMask != null; }
      set { if (value == (this._sensorMask== null)) this._sensorMask = value ? this.sensorMask : (uint?)null; }
    }
    private bool ShouldSerializesensorMask() { return sensorMaskSpecified; }
    private void ResetsensorMask() { sensorMaskSpecified = false; }
    
    private float? _quat_x_yaw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"quat_x_yaw", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float quat_x_yaw
    {
      get { return _quat_x_yaw?? default(float); }
      set { _quat_x_yaw = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool quat_x_yawSpecified
    {
      get { return this._quat_x_yaw != null; }
      set { if (value == (this._quat_x_yaw== null)) this._quat_x_yaw = value ? this.quat_x_yaw : (float?)null; }
    }
    private bool ShouldSerializequat_x_yaw() { return quat_x_yawSpecified; }
    private void Resetquat_x_yaw() { quat_x_yawSpecified = false; }
    
    private float? _quat_y_pitch;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"quat_y_pitch", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float quat_y_pitch
    {
      get { return _quat_y_pitch?? default(float); }
      set { _quat_y_pitch = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool quat_y_pitchSpecified
    {
      get { return this._quat_y_pitch != null; }
      set { if (value == (this._quat_y_pitch== null)) this._quat_y_pitch = value ? this.quat_y_pitch : (float?)null; }
    }
    private bool ShouldSerializequat_y_pitch() { return quat_y_pitchSpecified; }
    private void Resetquat_y_pitch() { quat_y_pitchSpecified = false; }
    
    private float? _quat_z_roll;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"quat_z_roll", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float quat_z_roll
    {
      get { return _quat_z_roll?? default(float); }
      set { _quat_z_roll = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool quat_z_rollSpecified
    {
      get { return this._quat_z_roll != null; }
      set { if (value == (this._quat_z_roll== null)) this._quat_z_roll = value ? this.quat_z_roll : (float?)null; }
    }
    private bool ShouldSerializequat_z_roll() { return quat_z_rollSpecified; }
    private void Resetquat_z_roll() { quat_z_rollSpecified = false; }
    
    private float? _quat_w;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"quat_w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float quat_w
    {
      get { return _quat_w?? default(float); }
      set { _quat_w = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool quat_wSpecified
    {
      get { return this._quat_w != null; }
      set { if (value == (this._quat_w== null)) this._quat_w = value ? this.quat_w : (float?)null; }
    }
    private bool ShouldSerializequat_w() { return quat_wSpecified; }
    private void Resetquat_w() { quat_wSpecified = false; }
    
    private int? _Mag_x;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Mag_x", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Mag_x
    {
      get { return _Mag_x?? default(int); }
      set { _Mag_x = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Mag_xSpecified
    {
      get { return this._Mag_x != null; }
      set { if (value == (this._Mag_x== null)) this._Mag_x = value ? this.Mag_x : (int?)null; }
    }
    private bool ShouldSerializeMag_x() { return Mag_xSpecified; }
    private void ResetMag_x() { Mag_xSpecified = false; }
    
    private int? _Mag_y;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Mag_y", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Mag_y
    {
      get { return _Mag_y?? default(int); }
      set { _Mag_y = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Mag_ySpecified
    {
      get { return this._Mag_y != null; }
      set { if (value == (this._Mag_y== null)) this._Mag_y = value ? this.Mag_y : (int?)null; }
    }
    private bool ShouldSerializeMag_y() { return Mag_ySpecified; }
    private void ResetMag_y() { Mag_ySpecified = false; }
    
    private int? _Mag_z;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Mag_z", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Mag_z
    {
      get { return _Mag_z?? default(int); }
      set { _Mag_z = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Mag_zSpecified
    {
      get { return this._Mag_z != null; }
      set { if (value == (this._Mag_z== null)) this._Mag_z = value ? this.Mag_z : (int?)null; }
    }
    private bool ShouldSerializeMag_z() { return Mag_zSpecified; }
    private void ResetMag_z() { Mag_zSpecified = false; }
    
    private int? _Accel_x;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Accel_x", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Accel_x
    {
      get { return _Accel_x?? default(int); }
      set { _Accel_x = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Accel_xSpecified
    {
      get { return this._Accel_x != null; }
      set { if (value == (this._Accel_x== null)) this._Accel_x = value ? this.Accel_x : (int?)null; }
    }
    private bool ShouldSerializeAccel_x() { return Accel_xSpecified; }
    private void ResetAccel_x() { Accel_xSpecified = false; }
    
    private int? _Accel_y;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"Accel_y", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Accel_y
    {
      get { return _Accel_y?? default(int); }
      set { _Accel_y = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Accel_ySpecified
    {
      get { return this._Accel_y != null; }
      set { if (value == (this._Accel_y== null)) this._Accel_y = value ? this.Accel_y : (int?)null; }
    }
    private bool ShouldSerializeAccel_y() { return Accel_ySpecified; }
    private void ResetAccel_y() { Accel_ySpecified = false; }
    
    private int? _Accel_z;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"Accel_z", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Accel_z
    {
      get { return _Accel_z?? default(int); }
      set { _Accel_z = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Accel_zSpecified
    {
      get { return this._Accel_z != null; }
      set { if (value == (this._Accel_z== null)) this._Accel_z = value ? this.Accel_z : (int?)null; }
    }
    private bool ShouldSerializeAccel_z() { return Accel_zSpecified; }
    private void ResetAccel_z() { Accel_zSpecified = false; }
    
    private int? _Rot_x;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Rot_x", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Rot_x
    {
      get { return _Rot_x?? default(int); }
      set { _Rot_x = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Rot_xSpecified
    {
      get { return this._Rot_x != null; }
      set { if (value == (this._Rot_x== null)) this._Rot_x = value ? this.Rot_x : (int?)null; }
    }
    private bool ShouldSerializeRot_x() { return Rot_xSpecified; }
    private void ResetRot_x() { Rot_xSpecified = false; }
    
    private int? _Rot_y;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"Rot_y", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Rot_y
    {
      get { return _Rot_y?? default(int); }
      set { _Rot_y = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Rot_ySpecified
    {
      get { return this._Rot_y != null; }
      set { if (value == (this._Rot_y== null)) this._Rot_y = value ? this.Rot_y : (int?)null; }
    }
    private bool ShouldSerializeRot_y() { return Rot_ySpecified; }
    private void ResetRot_y() { Rot_ySpecified = false; }
    
    private int? _Rot_z;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Rot_z", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Rot_z
    {
      get { return _Rot_z?? default(int); }
      set { _Rot_z = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Rot_zSpecified
    {
      get { return this._Rot_z != null; }
      set { if (value == (this._Rot_z== null)) this._Rot_z = value ? this.Rot_z : (int?)null; }
    }
    private bool ShouldSerializeRot_z() { return Rot_zSpecified; }
    private void ResetRot_z() { Rot_zSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullDataFrame")]
  public partial class FullDataFrame : global::ProtoBuf.IExtensible
  {
    public FullDataFrame() {}
    
    private uint _timeStamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timeStamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint timeStamp
    {
      get { return _timeStamp; }
      set { _timeStamp = value; }
    }
    private readonly global::System.Collections.Generic.List<DAL.Models.MongoDocuments.ImuDataFrame> _imuDataFrame = new global::System.Collections.Generic.List<DAL.Models.MongoDocuments.ImuDataFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"imuDataFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DAL.Models.MongoDocuments.ImuDataFrame> imuDataFrame
    {
      get { return _imuDataFrame; }
    }
  
    private DAL.Models.MongoDocuments.ReportType? _reportType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reportType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DAL.Models.MongoDocuments.ReportType reportType
    {
      get { return _reportType?? DAL.Models.MongoDocuments.ReportType.pain; }
      set { _reportType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reportTypeSpecified
    {
      get { return this._reportType != null; }
      set { if (value == (this._reportType== null)) this._reportType = value ? this.reportType : (DAL.Models.MongoDocuments.ReportType?)null; }
    }
    private bool ShouldSerializereportType() { return reportTypeSpecified; }
    private void ResetreportType() { reportTypeSpecified = false; }
    
    private string _gpsCoordinates;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gpsCoordinates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gpsCoordinates
    {
      get { return _gpsCoordinates?? ""; }
      set { _gpsCoordinates = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool gpsCoordinatesSpecified
    {
      get { return this._gpsCoordinates != null; }
      set { if (value == (this._gpsCoordinates== null)) this._gpsCoordinates = value ? this.gpsCoordinates : (string)null; }
    }
    private bool ShouldSerializegpsCoordinates() { return gpsCoordinatesSpecified; }
    private void ResetgpsCoordinates() { gpsCoordinatesSpecified = false; }
    
    private uint? _calibrationId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"calibrationId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint calibrationId
    {
      get { return _calibrationId?? default(uint); }
      set { _calibrationId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool calibrationIdSpecified
    {
      get { return this._calibrationId != null; }
      set { if (value == (this._calibrationId== null)) this._calibrationId = value ? this.calibrationId : (uint?)null; }
    }
    private bool ShouldSerializecalibrationId() { return calibrationIdSpecified; }
    private void ResetcalibrationId() { calibrationIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Endpoint")]
  public partial class Endpoint : global::ProtoBuf.IExtensible
  {
    public Endpoint() {}
    
    private string _address;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }
    private uint _port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WifiConfiguration")]
  public partial class WifiConfiguration : global::ProtoBuf.IExtensible
  {
    public WifiConfiguration() {}
    
    private string _ssid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ssid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ssid
    {
      get { return _ssid; }
      set { _ssid = value; }
    }
    private DAL.Models.MongoDocuments.WifiSecurityType _securityType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"securityType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DAL.Models.MongoDocuments.WifiSecurityType securityType
    {
      get { return _securityType; }
      set { _securityType = value; }
    }
    private bool _wifiState;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"wifiState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool wifiState
    {
      get { return _wifiState; }
      set { _wifiState = value; }
    }
    private string _passphrase;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"passphrase", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passphrase
    {
      get { return _passphrase?? ""; }
      set { _passphrase = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool passphraseSpecified
    {
      get { return this._passphrase != null; }
      set { if (value == (this._passphrase== null)) this._passphrase = value ? this.passphrase : (string)null; }
    }
    private bool ShouldSerializepassphrase() { return passphraseSpecified; }
    private void Resetpassphrase() { passphraseSpecified = false; }
    
    private uint? _udpBroadcastPort;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"udpBroadcastPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint udpBroadcastPort
    {
      get { return _udpBroadcastPort?? default(uint); }
      set { _udpBroadcastPort = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool udpBroadcastPortSpecified
    {
      get { return this._udpBroadcastPort != null; }
      set { if (value == (this._udpBroadcastPort== null)) this._udpBroadcastPort = value ? this.udpBroadcastPort : (uint?)null; }
    }
    private bool ShouldSerializeudpBroadcastPort() { return udpBroadcastPortSpecified; }
    private void ResetudpBroadcastPort() { udpBroadcastPortSpecified = false; }
    
    private uint? _connectionTimeout;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"connectionTimeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint connectionTimeout
    {
      get { return _connectionTimeout?? default(uint); }
      set { _connectionTimeout = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool connectionTimeoutSpecified
    {
      get { return this._connectionTimeout != null; }
      set { if (value == (this._connectionTimeout== null)) this._connectionTimeout = value ? this.connectionTimeout : (uint?)null; }
    }
    private bool ShouldSerializeconnectionTimeout() { return connectionTimeoutSpecified; }
    private void ResetconnectionTimeout() { connectionTimeoutSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecordingsResponse")]
  public partial class RecordingsResponse : global::ProtoBuf.IExtensible
  {
    public RecordingsResponse() {}
    
    private uint _recordingsCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"recordingsCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint recordingsCount
    {
      get { return _recordingsCount; }
      set { _recordingsCount = value; }
    }
    private uint _calibrationCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"calibrationCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint calibrationCount
    {
      get { return _calibrationCount; }
      set { _calibrationCount = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _recordingFilename = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"recordingFilename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> recordingFilename
    {
      get { return _recordingFilename; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _calibrationFilename = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"calibrationFilename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> calibrationFilename
    {
      get { return _calibrationFilename; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileDownload")]
  public partial class FileDownload : global::ProtoBuf.IExtensible
  {
    public FileDownload() {}
    
    private DAL.Models.MongoDocuments.Endpoint _downloadEndpoint;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"downloadEndpoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DAL.Models.MongoDocuments.Endpoint downloadEndpoint
    {
      get { return _downloadEndpoint; }
      set { _downloadEndpoint = value; }
    }
    private string _downloadFilename;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"downloadFilename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string downloadFilename
    {
      get { return _downloadFilename; }
      set { _downloadFilename = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FirmwareUpdate")]
  public partial class FirmwareUpdate : global::ProtoBuf.IExtensible
  {
    public FirmwareUpdate() {}
    
    private DAL.Models.MongoDocuments.Endpoint _fwEndpoint;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fwEndpoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DAL.Models.MongoDocuments.Endpoint fwEndpoint
    {
      get { return _fwEndpoint; }
      set { _fwEndpoint = value; }
    }
    private string _fwFilename;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fwFilename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fwFilename
    {
      get { return _fwFilename; }
      set { _fwFilename = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Packet")]
  public partial class Packet : global::ProtoBuf.IExtensible
  {
    public Packet() {}
    
    private DAL.Models.MongoDocuments.PacketType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DAL.Models.MongoDocuments.PacketType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private DAL.Models.MongoDocuments.BrainpackState? _brainpackState;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"brainpackState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DAL.Models.MongoDocuments.BrainpackState brainpackState
    {
      get { return _brainpackState?? DAL.Models.MongoDocuments.BrainpackState.Initializing; }
      set { _brainpackState = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool brainpackStateSpecified
    {
      get { return this._brainpackState != null; }
      set { if (value == (this._brainpackState== null)) this._brainpackState = value ? this.brainpackState : (DAL.Models.MongoDocuments.BrainpackState?)null; }
    }
    private bool ShouldSerializebrainpackState() { return brainpackStateSpecified; }
    private void ResetbrainpackState() { brainpackStateSpecified = false; }
    
    private string _firmwareVersion;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"firmwareVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string firmwareVersion
    {
      get { return _firmwareVersion?? ""; }
      set { _firmwareVersion = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool firmwareVersionSpecified
    {
      get { return this._firmwareVersion != null; }
      set { if (value == (this._firmwareVersion== null)) this._firmwareVersion = value ? this.firmwareVersion : (string)null; }
    }
    private bool ShouldSerializefirmwareVersion() { return firmwareVersionSpecified; }
    private void ResetfirmwareVersion() { firmwareVersionSpecified = false; }
    
    private string _serialNumber;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"serialNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serialNumber
    {
      get { return _serialNumber?? ""; }
      set { _serialNumber = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool serialNumberSpecified
    {
      get { return this._serialNumber != null; }
      set { if (value == (this._serialNumber== null)) this._serialNumber = value ? this.serialNumber : (string)null; }
    }
    private bool ShouldSerializeserialNumber() { return serialNumberSpecified; }
    private void ResetserialNumber() { serialNumberSpecified = false; }
    
    private uint? _batteryLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"batteryLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint batteryLevel
    {
      get { return _batteryLevel?? default(uint); }
      set { _batteryLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool batteryLevelSpecified
    {
      get { return this._batteryLevel != null; }
      set { if (value == (this._batteryLevel== null)) this._batteryLevel = value ? this.batteryLevel : (uint?)null; }
    }
    private bool ShouldSerializebatteryLevel() { return batteryLevelSpecified; }
    private void ResetbatteryLevel() { batteryLevelSpecified = false; }
    
    private DAL.Models.MongoDocuments.ChargeState? _chargeState;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"chargeState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DAL.Models.MongoDocuments.ChargeState chargeState
    {
      get { return _chargeState?? DAL.Models.MongoDocuments.ChargeState.BatteryLow; }
      set { _chargeState = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool chargeStateSpecified
    {
      get { return this._chargeState != null; }
      set { if (value == (this._chargeState== null)) this._chargeState = value ? this.chargeState : (DAL.Models.MongoDocuments.ChargeState?)null; }
    }
    private bool ShouldSerializechargeState() { return chargeStateSpecified; }
    private void ResetchargeState() { chargeStateSpecified = false; }
    
    private bool? _messageStatus;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"messageStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool messageStatus
    {
      get { return _messageStatus?? default(bool); }
      set { _messageStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool messageStatusSpecified
    {
      get { return this._messageStatus != null; }
      set { if (value == (this._messageStatus== null)) this._messageStatus = value ? this.messageStatus : (bool?)null; }
    }
    private bool ShouldSerializemessageStatus() { return messageStatusSpecified; }
    private void ResetmessageStatus() { messageStatusSpecified = false; }
    
    private string _calibrationFilename;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"calibrationFilename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string calibrationFilename
    {
      get { return _calibrationFilename?? ""; }
      set { _calibrationFilename = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool calibrationFilenameSpecified
    {
      get { return this._calibrationFilename != null; }
      set { if (value == (this._calibrationFilename== null)) this._calibrationFilename = value ? this.calibrationFilename : (string)null; }
    }
    private bool ShouldSerializecalibrationFilename() { return calibrationFilenameSpecified; }
    private void ResetcalibrationFilename() { calibrationFilenameSpecified = false; }
    
    private uint? _recordingRate;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"recordingRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint recordingRate
    {
      get { return _recordingRate?? default(uint); }
      set { _recordingRate = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool recordingRateSpecified
    {
      get { return this._recordingRate != null; }
      set { if (value == (this._recordingRate== null)) this._recordingRate = value ? this.recordingRate : (uint?)null; }
    }
    private bool ShouldSerializerecordingRate() { return recordingRateSpecified; }
    private void ResetrecordingRate() { recordingRateSpecified = false; }
    
    private string _recordingFilename;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"recordingFilename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string recordingFilename
    {
      get { return _recordingFilename?? ""; }
      set { _recordingFilename = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool recordingFilenameSpecified
    {
      get { return this._recordingFilename != null; }
      set { if (value == (this._recordingFilename== null)) this._recordingFilename = value ? this.recordingFilename : (string)null; }
    }
    private bool ShouldSerializerecordingFilename() { return recordingFilenameSpecified; }
    private void ResetrecordingFilename() { recordingFilenameSpecified = false; }
    
    private string _dateTime;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"dateTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dateTime
    {
      get { return _dateTime?? ""; }
      set { _dateTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dateTimeSpecified
    {
      get { return this._dateTime != null; }
      set { if (value == (this._dateTime== null)) this._dateTime = value ? this.dateTime : (string)null; }
    }
    private bool ShouldSerializedateTime() { return dateTimeSpecified; }
    private void ResetdateTime() { dateTimeSpecified = false; }
    
    private uint? _configurationPort;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"configurationPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint configurationPort
    {
      get { return _configurationPort?? default(uint); }
      set { _configurationPort = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool configurationPortSpecified
    {
      get { return this._configurationPort != null; }
      set { if (value == (this._configurationPort== null)) this._configurationPort = value ? this.configurationPort : (uint?)null; }
    }
    private bool ShouldSerializeconfigurationPort() { return configurationPortSpecified; }
    private void ResetconfigurationPort() { configurationPortSpecified = false; }
    
    private uint? _sensorMask;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"sensorMask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sensorMask
    {
      get { return _sensorMask?? default(uint); }
      set { _sensorMask = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sensorMaskSpecified
    {
      get { return this._sensorMask != null; }
      set { if (value == (this._sensorMask== null)) this._sensorMask = value ? this.sensorMask : (uint?)null; }
    }
    private bool ShouldSerializesensorMask() { return sensorMaskSpecified; }
    private void ResetsensorMask() { sensorMaskSpecified = false; }
    
    private DAL.Models.MongoDocuments.WifiConfiguration _wifiConfiguration = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"wifiConfiguration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DAL.Models.MongoDocuments.WifiConfiguration wifiConfiguration
    {
      get { return _wifiConfiguration; }
      set { _wifiConfiguration = value; }
    }
    private DAL.Models.MongoDocuments.RecordingsResponse _recordingsResponse = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"recordingsResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DAL.Models.MongoDocuments.RecordingsResponse recordingsResponse
    {
      get { return _recordingsResponse; }
      set { _recordingsResponse = value; }
    }
    private DAL.Models.MongoDocuments.FileDownload _fileDownload = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"fileDownload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DAL.Models.MongoDocuments.FileDownload fileDownload
    {
      get { return _fileDownload; }
      set { _fileDownload = value; }
    }
    private DAL.Models.MongoDocuments.FirmwareUpdate _firmwareUpdate = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"firmwareUpdate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DAL.Models.MongoDocuments.FirmwareUpdate firmwareUpdate
    {
      get { return _firmwareUpdate; }
      set { _firmwareUpdate = value; }
    }
    private DAL.Models.MongoDocuments.FullDataFrame _fullDataFrame = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"fullDataFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DAL.Models.MongoDocuments.FullDataFrame fullDataFrame
    {
      get { return _fullDataFrame; }
      set { _fullDataFrame = value; }
    }
    private DAL.Models.MongoDocuments.Endpoint _endpoint = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"endpoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DAL.Models.MongoDocuments.Endpoint endpoint
    {
      get { return _endpoint; }
      set { _endpoint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PacketType")]
    public enum PacketType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"StatusRequest", Value=0)]
      StatusRequest = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StatusResponse", Value=1)]
      StatusResponse = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetWifiConfiguration", Value=2)]
      SetWifiConfiguration = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RecordingsListRequest", Value=3)]
      RecordingsListRequest = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RecordingListReponse", Value=4)]
      RecordingListReponse = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FileDownloadRequest", Value=5)]
      FileDownloadRequest = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FileDownloadReponse", Value=6)]
      FileDownloadReponse = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClearBrainpackRequest", Value=7)]
      ClearBrainpackRequest = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CalibrationRequest", Value=8)]
      CalibrationRequest = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CalibrationResponse", Value=9)]
      CalibrationResponse = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartDataStream", Value=10)]
      StartDataStream = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StopDataStream", Value=11)]
      StopDataStream = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ConfigureRecordingSettings", Value=12)]
      ConfigureRecordingSettings = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DataFrame", Value=13)]
      DataFrame = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RecordingInformation", Value=14)]
      RecordingInformation = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LastCalibrationRequest", Value=15)]
      LastCalibrationRequest = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LastCalibrationResponse", Value=16)]
      LastCalibrationResponse = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AdvertisingPacket", Value=17)]
      AdvertisingPacket = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateFirmwareRequest", Value=18)]
      UpdateFirmwareRequest = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatedFirmwareResponse", Value=19)]
      UpdatedFirmwareResponse = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetTimeRequest", Value=20)]
      SetTimeRequest = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MessageStatus", Value=21)]
      MessageStatus = 21
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BrainpackState")]
    public enum BrainpackState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Initializing", Value=0)]
      Initializing = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Idle", Value=1)]
      Idle = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Recording", Value=2)]
      Recording = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Streaming", Value=3)]
      Streaming = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error", Value=4)]
      Error = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChargeState")]
    public enum ChargeState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatteryLow", Value=0)]
      BatteryLow = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatteryNominal", Value=1)]
      BatteryNominal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatteryFull", Value=2)]
      BatteryFull = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Charging", Value=3)]
      Charging = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ReportType")]
    public enum ReportType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"pain", Value=0)]
      pain = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"concern", Value=1)]
      concern = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"WifiSecurityType")]
    public enum WifiSecurityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEP", Value=0)]
      WEP = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WPA", Value=1)]
      WPA = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Open", Value=3)]
      Open = 3
    }
}
