//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("i18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new.
        /// </summary>
        public static string AddANew {
            get {
                return ResourceManager.GetString("AddANew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heddoko Admin.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anatomical position.
        /// </summary>
        public static string AnatomicalPosition {
            get {
                return ResourceManager.GetString("AnatomicalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anatomical positions.
        /// </summary>
        public static string AnatomicalPositions {
            get {
                return ResourceManager.GetString("AnatomicalPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Fore Arm.
        /// </summary>
        public static string AnatomicalPositionType_LeftForeArm {
            get {
                return ResourceManager.GetString("AnatomicalPositionType_LeftForeArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thigh.
        /// </summary>
        public static string AnatomicalPositionType_LeftThigh {
            get {
                return ResourceManager.GetString("AnatomicalPositionType_LeftThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Tibia.
        /// </summary>
        public static string AnatomicalPositionType_LeftTibia {
            get {
                return ResourceManager.GetString("AnatomicalPositionType_LeftTibia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Upper Arm.
        /// </summary>
        public static string AnatomicalPositionType_LeftUpperArm {
            get {
                return ResourceManager.GetString("AnatomicalPositionType_LeftUpperArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Fore Arm.
        /// </summary>
        public static string AnatomicalPositionType_RightForeArm {
            get {
                return ResourceManager.GetString("AnatomicalPositionType_RightForeArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thigh.
        /// </summary>
        public static string AnatomicalPositionType_RightThigh {
            get {
                return ResourceManager.GetString("AnatomicalPositionType_RightThigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Tibia.
        /// </summary>
        public static string AnatomicalPositionType_RightTibia {
            get {
                return ResourceManager.GetString("AnatomicalPositionType_RightTibia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Upper Arm.
        /// </summary>
        public static string AnatomicalPositionType_RightUpperArm {
            get {
                return ResourceManager.GetString("AnatomicalPositionType_RightUpperArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Spine.
        /// </summary>
        public static string AnatomicalPositionType_UpperSpine {
            get {
                return ResourceManager.GetString("AnatomicalPositionType_UpperSpine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add duplicate.
        /// </summary>
        public static string CannotAddDuplicate {
            get {
                return ResourceManager.GetString("CannotAddDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete, because.
        /// </summary>
        public static string CannotRemove {
            get {
                return ResourceManager.GetString("CannotRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suit.
        /// </summary>
        public static string ComplexEquipment {
            get {
                return ResourceManager.GetString("ComplexEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suits.
        /// </summary>
        public static string ComplexEquipments {
            get {
                return ResourceManager.GetString("ComplexEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ConditionType_New {
            get {
                return ResourceManager.GetString("ConditionType_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string ConditionType_Used {
            get {
                return ResourceManager.GetString("ConditionType_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form to confirm your account.
        /// </summary>
        public static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match.
        /// </summary>
        public static string ConfirmPasswordValidateMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm token.
        /// </summary>
        public static string ConfirmToken {
            get {
                return ResourceManager.GetString("ConfirmToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data anaylysis amount.
        /// </summary>
        public static string DataAnalysisAmount {
            get {
                return ResourceManager.GetString("DataAnalysisAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collectors amount.
        /// </summary>
        public static string DataCollectorAmount {
            get {
                return ResourceManager.GetString("DataCollectorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Description.
        /// </summary>
        public static string DetailedDescription {
            get {
                return ResourceManager.GetString("DetailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been activated.
        /// </summary>
        public static string EmailActivatedBody {
            get {
                return ResourceManager.GetString("EmailActivatedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated!.
        /// </summary>
        public static string EmailActivatedSubject {
            get {
                return ResourceManager.GetString("EmailActivatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string EmailActivationUserSubject {
            get {
                return ResourceManager.GetString("EmailActivationUserSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string EmailForgotPasswordSubject {
            get {
                return ResourceManager.GetString("EmailForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind username.
        /// </summary>
        public static string EmailForgotUsernameSubject {
            get {
                return ResourceManager.GetString("EmailForgotUsernameSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You become as admin of organization.
        /// </summary>
        public static string EmailInviteAdminUserSubject {
            get {
                return ResourceManager.GetString("EmailInviteAdminUserSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You invited to organization.
        /// </summary>
        public static string EmailInviteUserSubject {
            get {
                return ResourceManager.GetString("EmailInviteUserSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already used.
        /// </summary>
        public static string EmailUsed {
            get {
                return ResourceManager.GetString("EmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty confirmation token.
        /// </summary>
        public static string EmptyConfirmationToken {
            get {
                return ResourceManager.GetString("EmptyConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty forgot token.
        /// </summary>
        public static string EmptyForgotToken {
            get {
                return ResourceManager.GetString("EmptyForgotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item to display.
        /// </summary>
        public static string EmptyItems {
            get {
                return ResourceManager.GetString("EmptyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license.
        /// </summary>
        public static string EmptyLicense {
            get {
                return ResourceManager.GetString("EmptyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a MAC address, a physical location, or a serial #.
        /// </summary>
        public static string EnterComplexEquipment {
            get {
                return ResourceManager.GetString("EnterComplexEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the serial # or location or mac address of an equipment.
        /// </summary>
        public static string EnterEquipment {
            get {
                return ResourceManager.GetString("EnterEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an identifier.
        /// </summary>
        public static string EnterIdentifier {
            get {
                return ResourceManager.GetString("EnterIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the id of license.
        /// </summary>
        public static string EnterLicense {
            get {
                return ResourceManager.GetString("EnterLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name or part # of a material.
        /// </summary>
        public static string EnterMaterial {
            get {
                return ResourceManager.GetString("EnterMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name or id or phone of organization.
        /// </summary>
        public static string EnterOrganization {
            get {
                return ResourceManager.GetString("EnterOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the firstname or lastname or email of user.
        /// </summary>
        public static string EnterUser {
            get {
                return ResourceManager.GetString("EnterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments.
        /// </summary>
        public static string Equipments {
            get {
                return ResourceManager.GetString("Equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string EquipmentStatusType_Available {
            get {
                return ResourceManager.GetString("EquipmentStatusType_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In transit.
        /// </summary>
        public static string EquipmentStatusType_InTransit {
            get {
                return ResourceManager.GetString("EquipmentStatusType_InTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On loan.
        /// </summary>
        public static string EquipmentStatusType_OnLoan {
            get {
                return ResourceManager.GetString("EquipmentStatusType_OnLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string EquipmentStatusType_Unavailable {
            get {
                return ResourceManager.GetString("EquipmentStatusType_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration at.
        /// </summary>
        public static string ExpirationAt {
            get {
                return ResourceManager.GetString("ExpirationAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot token is expired.
        /// </summary>
        public static string ExpiredForgotToken {
            get {
                return ResourceManager.GetString("ExpiredForgotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your username?.
        /// </summary>
        public static string ForgotYourUsername {
            get {
                return ResourceManager.GetString("ForgotYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatshrink good.
        /// </summary>
        public static string HeatsShrink {
            get {
                return ResourceManager.GetString("HeatsShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string HeatsShrinkType_No {
            get {
                return ResourceManager.GetString("HeatsShrinkType_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string HeatsShrinkType_Yes {
            get {
                return ResourceManager.GetString("HeatsShrinkType_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heddoko.
        /// </summary>
        public static string Heddoko {
            get {
                return ResourceManager.GetString("Heddoko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Importance.
        /// </summary>
        public static string Importance {
            get {
                return ResourceManager.GetString("Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form to apply you invite.
        /// </summary>
        public static string InviteMessage {
            get {
                return ResourceManager.GetString("InviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite token.
        /// </summary>
        public static string InviteToken {
            get {
                return ResourceManager.GetString("InviteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show stopper.
        /// </summary>
        public static string IssueImportance_High {
            get {
                return ResourceManager.GetString("IssueImportance_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can live with it now.
        /// </summary>
        public static string IssueImportance_Low {
            get {
                return ResourceManager.GetString("IssueImportance_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t prevent me from working.
        /// </summary>
        public static string IssueImportance_Medium {
            get {
                return ResourceManager.GetString("IssueImportance_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue type.
        /// </summary>
        public static string IssueType {
            get {
                return ResourceManager.GetString("IssueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Issue.
        /// </summary>
        public static string IssueType_Hardware {
            get {
                return ResourceManager.GetString("IssueType_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Feature Request.
        /// </summary>
        public static string IssueType_NewFeature {
            get {
                return ResourceManager.GetString("IssueType_NewFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Issue.
        /// </summary>
        public static string IssueType_Software {
            get {
                return ResourceManager.GetString("IssueType_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License dashboard.
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data analysis.
        /// </summary>
        public static string LicenseType_DataAnalysis {
            get {
                return ResourceManager.GetString("LicenseType_DataAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collection.
        /// </summary>
        public static string LicenseType_DataCollection {
            get {
                return ResourceManager.GetString("LicenseType_DataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License already used.
        /// </summary>
        public static string LicenseUsed {
            get {
                return ResourceManager.GetString("LicenseUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License amount can&apos;t be less than used.
        /// </summary>
        public static string LiceseAmountUsed {
            get {
                return ResourceManager.GetString("LiceseAmountUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        public static string MacAddress {
            get {
                return ResourceManager.GetString("MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material type.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string MaterialType_Battery {
            get {
                return ResourceManager.GetString("MaterialType_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        public static string MaterialType_Sensor {
            get {
                return ResourceManager.GetString("MaterialType_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Types.
        /// </summary>
        public static string MaterialTypes {
            get {
                return ResourceManager.GetString("MaterialTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string MovementEventType_Jump {
            get {
                return ResourceManager.GetString("MovementEventType_Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing.
        /// </summary>
        public static string MovementEventType_Standing {
            get {
                return ResourceManager.GetString("MovementEventType_Standing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NumbersType_No {
            get {
                return ResourceManager.GetString("NumbersType_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string NumbersType_Yes {
            get {
                return ResourceManager.GetString("NumbersType_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Whoops!&lt;/strong&gt; There were some problems with your input.&lt;br&gt;&lt;br&gt;.
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of organization.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of organization in use..
        /// </summary>
        public static string OrganizationNameUsed {
            get {
                return ResourceManager.GetString("OrganizationNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part #.
        /// </summary>
        public static string PartNo {
            get {
                return ResourceManager.GetString("PartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address that you used to register. We&apos;ll send you an email with your username and a link to reset your password..
        /// </summary>
        public static string PasswordForgotMessage {
            get {
                return ResourceManager.GetString("PasswordForgotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Successfully Changed.
        /// </summary>
        public static string PasswordSuccessufullyChanged {
            get {
                return ResourceManager.GetString("PasswordSuccessufullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent an email with a link to reset a password.
        /// </summary>
        public static string PasswordSuccessufullySent {
            get {
                return ResourceManager.GetString("PasswordSuccessufullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical location.
        /// </summary>
        public static string PhysicalLocation {
            get {
                return ResourceManager.GetString("PhysicalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You profile have been updated.
        /// </summary>
        public static string ProfileSaveMessage {
            get {
                return ResourceManager.GetString("ProfileSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prototype.
        /// </summary>
        public static string Prototype {
            get {
                return ResourceManager.GetString("Prototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string PrototypeType_No {
            get {
                return ResourceManager.GetString("PrototypeType_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PrototypeType_Yes {
            get {
                return ResourceManager.GetString("PrototypeType_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form to reset your password..
        /// </summary>
        public static string ResetPasswordMessage {
            get {
                return ResourceManager.GetString("ResetPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Username.
        /// </summary>
        public static string RetrieveUsername {
            get {
                return ResourceManager.GetString("RetrieveUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an anatomical position.
        /// </summary>
        public static string SelectAnatomicalPosition {
            get {
                return ResourceManager.GetString("SelectAnatomicalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a condition.
        /// </summary>
        public static string SelectCondition {
            get {
                return ResourceManager.GetString("SelectCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a equipments.
        /// </summary>
        public static string SelectEquipment {
            get {
                return ResourceManager.GetString("SelectEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a heats shrink.
        /// </summary>
        public static string SelectHeatsShrink {
            get {
                return ResourceManager.GetString("SelectHeatsShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a material.
        /// </summary>
        public static string SelectMaterial {
            get {
                return ResourceManager.GetString("SelectMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a material type.
        /// </summary>
        public static string SelectMaterialType {
            get {
                return ResourceManager.GetString("SelectMaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a number.
        /// </summary>
        public static string SelectNumber {
            get {
                return ResourceManager.GetString("SelectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a prototype.
        /// </summary>
        public static string SelectPrototype {
            get {
                return ResourceManager.GetString("SelectPrototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a ready ship.
        /// </summary>
        public static string SelectShip {
            get {
                return ResourceManager.GetString("SelectShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a status.
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select verified by.
        /// </summary>
        public static string SelectVerifiedBy {
            get {
                return ResourceManager.GetString("SelectVerifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial #.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string Ship {
            get {
                return ResourceManager.GetString("Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gone.
        /// </summary>
        public static string ShipType_Gone {
            get {
                return ResourceManager.GetString("ShipType_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ShipType_No {
            get {
                return ResourceManager.GetString("ShipType_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ShipType_Yes {
            get {
                return ResourceManager.GetString("ShipType_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show deleted.
        /// </summary>
        public static string ShowDeleted {
            get {
                return ResourceManager.GetString("ShowDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Than Just a Coach.
        /// </summary>
        public static string SignInInspiring {
            get {
                return ResourceManager.GetString("SignInInspiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string SignInInviteMessage {
            get {
                return ResourceManager.GetString("SignInInviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in now.
        /// </summary>
        public static string SignInMessage {
            get {
                return ResourceManager.GetString("SignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suit.
        /// </summary>
        public static string Suit {
            get {
                return ResourceManager.GetString("Suit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suits.
        /// </summary>
        public static string Suits {
            get {
                return ResourceManager.GetString("Suits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent an email with your support request. Soon we will contact with you..
        /// </summary>
        public static string SupportSent {
            get {
                return ResourceManager.GetString("SupportSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking on Sign up, you agree to &lt;br&gt; our.
        /// </summary>
        public static string TermMessage {
            get {
                return ResourceManager.GetString("TermMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms &amp; conditions.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heddoko | Track your movement in 3D.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink.
        /// </summary>
        public static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User used in another Organization.
        /// </summary>
        public static string UserAlreadyInOrganizations {
            get {
                return ResourceManager.GetString("UserAlreadyInOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string UserGenderType_Female {
            get {
                return ResourceManager.GetString("UserGenderType_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string UserGenderType_Male {
            get {
                return ResourceManager.GetString("UserGenderType_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSpecified.
        /// </summary>
        public static string UserGenderType_NotSpecified {
            get {
                return ResourceManager.GetString("UserGenderType_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is banned.
        /// </summary>
        public static string UserIsBanned {
            get {
                return ResourceManager.GetString("UserIsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserIsExists {
            get {
                return ResourceManager.GetString("UserIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not activated.
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address that you used to register. We&apos;ll send you an email with your username..
        /// </summary>
        public static string UsernameForgotMessage {
            get {
                return ResourceManager.GetString("UsernameForgotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent an email with your username..
        /// </summary>
        public static string UsernameSuccessufullySent {
            get {
                return ResourceManager.GetString("UsernameSuccessufullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already used.
        /// </summary>
        public static string UsernameUsed {
            get {
                return ResourceManager.GetString("UsernameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string UserRoleType_Admin {
            get {
                return ResourceManager.GetString("UserRoleType_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyst.
        /// </summary>
        public static string UserRoleType_Analyst {
            get {
                return ResourceManager.GetString("UserRoleType_Analyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License manager.
        /// </summary>
        public static string UserRoleType_LicenseAdmin {
            get {
                return ResourceManager.GetString("UserRoleType_LicenseAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserRoleType_User {
            get {
                return ResourceManager.GetString("UserRoleType_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User have been created. We have sent email with activation link, please activate your account..
        /// </summary>
        public static string UserSignupMessage {
            get {
                return ResourceManager.GetString("UserSignupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been updated. Now you can use your organization.
        /// </summary>
        public static string UserSignupOrganizationMessage {
            get {
                return ResourceManager.GetString("UserSignupOrganizationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been updated. Ask admin of your organization for license..
        /// </summary>
        public static string UserSignupUserNonLicenseOrganizationMessage {
            get {
                return ResourceManager.GetString("UserSignupUserNonLicenseOrganizationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been updated. Now you can use your account in application..
        /// </summary>
        public static string UserSignupUserOrganizationMessage {
            get {
                return ResourceManager.GetString("UserSignupUserOrganizationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string UserStatusType_Active {
            get {
                return ResourceManager.GetString("UserStatusType_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        public static string UserStatusType_Banned {
            get {
                return ResourceManager.GetString("UserStatusType_Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string UserStatusType_NotActive {
            get {
                return ResourceManager.GetString("UserStatusType_NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-mail field is not a valid e-mail address.
        /// </summary>
        public static string ValidateEmailMessage {
            get {
                return ResourceManager.GetString("ValidateEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ValidateLengthMessage {
            get {
                return ResourceManager.GetString("ValidateLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be from {2} to {1} characters long.
        /// </summary>
        public static string ValidateLengthRangeMessage {
            get {
                return ResourceManager.GetString("ValidateLengthRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be longer than {2} characters long..
        /// </summary>
        public static string ValidateMaxLengthMessage {
            get {
                return ResourceManager.GetString("ValidateMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required.
        /// </summary>
        public static string ValidateRequiredMessage {
            get {
                return ResourceManager.GetString("ValidateRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified by.
        /// </summary>
        public static string VerifiedBy {
            get {
                return ResourceManager.GetString("VerifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size can&apos;t be more than 20 mb..
        /// </summary>
        public static string WrongAttachmentSize {
            get {
                return ResourceManager.GetString("WrongAttachmentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong confirmation token.
        /// </summary>
        public static string WrongConfirmationToken {
            get {
                return ResourceManager.GetString("WrongConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found with that email address.
        /// </summary>
        public static string WrongEmailForgotPassword {
            get {
                return ResourceManager.GetString("WrongEmailForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date should be more than today.
        /// </summary>
        public static string WrongExpirationAtDate {
            get {
                return ResourceManager.GetString("WrongExpirationAtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid forgot token.
        /// </summary>
        public static string WrongForgotToken {
            get {
                return ResourceManager.GetString("WrongForgotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is not active.
        /// </summary>
        public static string WrongLicenseActive {
            get {
                return ResourceManager.GetString("WrongLicenseActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin can&apos;t be a license admin.
        /// </summary>
        public static string WrongLicenseAdmin {
            get {
                return ResourceManager.GetString("WrongLicenseAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is removed.
        /// </summary>
        public static string WrongLicenseDeleted {
            get {
                return ResourceManager.GetString("WrongLicenseDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is expired.
        /// </summary>
        public static string WrongLicenseExpiration {
            get {
                return ResourceManager.GetString("WrongLicenseExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t access to that object.
        /// </summary>
        public static string WrongObjectAccess {
            get {
                return ResourceManager.GetString("WrongObjectAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These credentials do not match our records..
        /// </summary>
        public static string WrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("WrongUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed.
        /// </summary>
        public static string YouAreNotAllowed {
            get {
                return ResourceManager.GetString("YouAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized.
        /// </summary>
        public static string YouAreNotAuthorized {
            get {
                return ResourceManager.GetString("YouAreNotAuthorized", resourceCulture);
            }
        }
    }
}
