namespace DAL.Models
{
    public enum BrainpackQAStatusType
    {
        TestedAndReady = 0,
        Fail = 1,
        Buttons1mmOfRecessPass = 2,
        Buttons1mmOfRecessFail = 3,
        ButtonsReturnToInitialDepthPass = 4,
        ButtonsReturnToInitialDepthFail = 5,
        PowerButtonWorkingPass = 6,
        PowerButtonWorkingFail = 7,
        ResetButtonWorkingPass = 8,
        ResetButtonWorkingFail = 9,
        RecordButtonWorkingPass = 10,
        RecordButtonWorkingFail = 11,
        ChargingIndicatorLedPass = 12,
        ChargingIndicatorLedFail = 13,
        StateIndicatorLedPass = 14,
        StateIndicatorLedFail = 15,
        LedColorsPass = 16,
        LedColorsFail = 17,
        SettingsFileUpdatedPass = 18,
        SettingsFileUpdatedFail = 19,
        PairingWithIMUsPass = 20,
        PairingWithIMUsFail = 21,
        SDCardIsElectronicallyLabeledWithBatteryPackIdPass = 22,
        SDCardIsElectronicallyLabeledWithBatteryPackIdFail = 23,
        AppPairsBrainpackPass = 24,
        AppPairsBrainpackFail = 25,
        AppLocatesBrainpackPass = 26,
        AppLocatesBrainpackFail = 27,
        AppConnectsToBrainpackPass = 28,
        AppConnectsToBrainpackFail = 29,
        AppDisconnectsFromBrainpackPass = 30,
        AppDisconnectsFromBrainpackFail = 31,
        StateChangeIdleToRecordingPass = 32,
        StateChangeIdleToRecordingFail = 33,
        StateChangeRecordingToIdlePass = 34,
        StateChangeRecordingToIdleFail = 35,
        StateChangeRecordingToResetPass = 36,
        StateChangeRecordingToResetFail = 37,
        StateChangeIdleToResetPass = 38,
        StateChangeIdleToResetFail = 39,
        StateChangeRecordingToErrorPass = 40,
        StateChangeRecordingToErrorFail = 41,
        RecoveryFromShutdownPass = 42,
        RecoveryFromShutdownFail = 43,
        SetRecordingNamePass = 44,
        SetRecordingNameFail = 45,
        RecordingFilenameSavedPass = 46,
        RecordingFilenameSavedFail = 47,
        FullChargingCyclePass = 48,
        FullChargingCycleFail = 49
    }
}
